version: '2.1'
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=galery
    ports:
      - "5435:5432"
    networks:
      - proxy_net
  node:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/galery
    networks:
      - proxy_net
    ports:
      - "1437:1437"
    depends_on:
      - database
    environment:
      PORT: 1337
      DB_URL: postgres://user@database/galery
      IMAGE_URL: http://127.0.0.1:1437/image/
networks:
  proxy_net:
    external: true
